import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Excursion
 * Id: 08958491-9d29-4b76-bf62-b6b7d27c99b4
 * Codename: excursion
 */
export type Excursion = IContentItem<{
    /**
     * Description (rich_text)
     * Required: false
     * Id: 03a718d8-074c-47a2-b300-ae1c73c86c21
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Destination (rich_text)
     * Required: false
     * Id: 9bb18daf-9163-42e8-bcad-1470de98b98a
     * Codename: destination
     */
    destination: Elements.RichTextElement;

    /**
     * Duration (Half Day/Full Day) (text)
     * Required: false
     * Id: ccbb2b3d-9b6a-4cc7-8a9d-77f85cef3400
     * Codename: duration__half_day_full_day_
     */
    durationHalfDayFullDay: Elements.TextElement;

    /**
     * Price in £ pp (number)
     * Required: false
     * Id: 3d5844b1-ecba-43d4-9408-ca8e5d711949
     * Codename: price_in___pp
     */
    priceInPp: Elements.NumberElement;
}>;
