import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Excursion
 * Id: 6a06cc0f-48d1-4716-8692-2fd1fc2ed3ba
 * Codename: excursion
 */
export type Excursion = IContentItem<{
  /**
   * Description (text)
   * Required: false
   * Id: 3882418b-92e4-470e-b323-790dfee359a3
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * Duration (multiple_choice)
   * Required: false
   * Id: 03f9f273-7574-4e8b-8c97-b3d6d71b982a
   * Codename: duration
   */
  duration: Elements.MultipleChoiceElement;

  /**
   * Name (text)
   * Required: false
   * Id: 3c4d3a14-410f-46be-9d29-b264991951ea
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Price in £ pp (number)
   * Required: false
   * Id: ff1b07fd-9774-4479-bcb1-c04d36c0c99a
   * Codename: price_in_pound_pp
   */
  priceInPoundPp: Elements.NumberElement;
}>;
