import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Tour } from './tour';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Export Module
 * Id: 446719ae-3c3b-48b0-b824-000594043d43
 * Codename: export_module
 */
export type ExportModule = IContentItem<{
    /**
     * Export to CSV (custom)
     * Required: false
     * Id: 0634cc12-0ef4-4b03-874c-f267aec175ac
     * Codename: export_to_csv
     */
    exportToCsv: Elements.CustomElement;

    /**
     * Tours to export (modular_content)
     * Required: false
     * Id: bcfc6a84-beab-471a-8e03-c9e4e5d924ff
     * Codename: tours_to_export
     */
    toursToExport: Elements.LinkedItemsElement<Tour>;
}>;
