import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Tour } from './tour';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Export Module
 * Id: e85cbb10-843e-46c2-baa0-c78ac6297a4f
 * Codename: export_module
 */
export type ExportModule = IContentItem<{
  /**
   * Export to CSV (custom)
   * Required: false
   * Id: 5b238f1e-0a58-43ea-9476-735fa9d31955
   * Codename: export_to_csv
   */
  exportToCsv: Elements.CustomElement;

  /**
   * Include hotel data (multiple_choice)
   * Required: false
   * Id: fc7eee04-fea6-47c1-8a42-7bdabba42288
   * Codename: include_hotel_data
   */
  includeHotelData: Elements.MultipleChoiceElement;

  /**
   * Tours to be exported (modular_content)
   * Required: false
   * Id: 4b804b94-c83c-4417-b752-7dfdd93c9b5b
   * Codename: tours_to_be_exported
   */
  toursToBeExported: Elements.LinkedItemsElement<Tour>;
}>;
