import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Hotel
 * Id: a2f6a55d-8b15-428a-a271-148e3969a815
 * Codename: hotel
 */
export type Hotel = IContentItem<{
  /**
   * Description (text)
   * Required: false
   * Id: 7ba164ee-5657-434c-8bcc-3dee525cedb0
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * Accessibility information (text)
   * Required: false
   * Id: 85125ac7-71f9-4989-ba64-4ace0c853284
   * Codename: hotel_accessibility_information
   */
  hotelAccessibilityInformation: Elements.TextElement;

  /**
   * Name (text)
   * Required: false
   * Id: 115f7825-6bd0-4025-874f-d8baa347a793
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Rating (text)
   * Required: false
   * Id: abcdcf7f-dd3f-4973-a891-e626cb3731c3
   * Codename: rating
   */
  rating: Elements.TextElement;
}>;
