import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Hotel
 * Id: d01c04c4-cc44-49df-b0c1-2abf703b0360
 * Codename: hotel
 */
export type Hotel = IContentItem<{
    /**
     * Accessibility Information (text)
     * Required: false
     * Id: 9a90a892-7e67-40c4-bfc6-cd6ac4d60b63
     * Codename: accessibility_information
     */
    accessibilityInformation: Elements.TextElement;

    /**
     * Description (rich_text)
     * Required: false
     * Id: ada93ab5-a20f-43af-9e29-5d7bfac08d15
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Name (rich_text)
     * Required: false
     * Id: e1b01826-4674-4d67-a058-a522edc97a28
     * Codename: name
     */
    name: Elements.RichTextElement;

    /**
     * Rating (text)
     * Required: false
     * Id: 6d703ef0-308e-4356-b406-8ad46d39333d
     * Codename: rating
     */
    rating: Elements.TextElement;
}>;
