import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Page
 * Id: 3ca89ab9-e78b-4932-9d6b-a87ea3197d62
 * Codename: page
 */
export type Page = IContentItem<{
    /**
     * Content (modular_content)
     * Required: false
     * Id: a3e9800d-4e6c-4e34-8e62-019d775eb076
     * Codename: content
     */
    content: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Show in navigation (multiple_choice)
     * Required: false
     * Id: a81d8dae-b77f-41a6-be9a-61b244e4d25d
     * Codename: show_in_navigation
     */
    showInNavigation: Elements.MultipleChoiceElement;

    /**
     * Subpages (subpages)
     * Required: false
     * Id: 1e36b1f4-0d45-47d5-b290-b4c2f17340e7
     * Codename: subpages
     */
    subpages: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Title (text)
     * Required: false
     * Id: 7c51f09f-2ddc-47cb-ad4f-c91a2effd38a
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * URL (url_slug)
     * Required: false
     * Id: c8757f25-632f-4432-b37b-1155f968889d
     * Codename: url
     */
    url: Elements.UrlSlugElement;
}>;
