import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Page
 * Id: fb007b3d-6b80-447a-a9ab-84bfda7ee473
 * Codename: page
 */
export type Page = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: b17ae350-66b6-4b4a-ab79-6078ccb09bcc
   * Codename: content
   */
  content: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Show in navigation (multiple_choice)
   * Required: false
   * Id: 2b252d37-f2ec-4c54-907f-5ebb811037a3
   * Codename: show_in_navigation
   */
  showInNavigation: Elements.MultipleChoiceElement;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: dba63878-8e20-4268-91a0-850c91ac91b2
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Title (text)
   * Required: false
   * Id: da9b82ab-01c4-40ba-a3be-9b836f723ce9
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL (url_slug)
   * Required: false
   * Id: 6c83acf0-2866-4e16-ada0-3ee63137ab13
   * Codename: url
   */
  url: Elements.UrlSlugElement;
}>;
