import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Place
 * Id: a645c9b3-bee7-4f38-96f2-717ad3513cf9
 * Codename: place
 */
export type Place = IContentItem<{
  /**
   * Name (text)
   * Required: false
   * Id: 9a808484-cb90-40b6-8f58-0acbf79b8404
   * Codename: name
   */
  name: Elements.TextElement;
}>;
