import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Tour } from './tour';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Web spotlight root
 * Id: 9cea5a27-7770-4c25-9503-d64b99320d96
 * Codename: web_spotlight_root
 */
export type WebSpotlightRoot = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 4e26fcf1-a2fa-4f20-8b1d-37aba61452b6
   * Codename: content
   */
  content: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: 84450bcf-f1e2-4e3c-b6ea-8f07046dca51
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<Tour>;

  /**
   * Title (text)
   * Required: false
   * Id: bcc9b2b7-ed2c-4a8f-b766-15beb95e9f09
   * Codename: title
   */
  title: Elements.TextElement;
}>;
