import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Page } from './page';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Web spotlight root
 * Id: e9a559db-bf98-479a-8472-b720c178fbaf
 * Codename: web_spotlight_root
 */
export type WebSpotlightRoot = IContentItem<{
    /**
     * Content (modular_content)
     * Required: false
     * Id: 54ba35ec-9f44-45c4-a8f5-fdf9a3944c26
     * Codename: content
     */
    content: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Subpages (subpages)
     * Required: false
     * Id: d6939665-1984-44f1-88ae-c45489114190
     * Codename: subpages
     */
    subpages: Elements.LinkedItemsElement<Page>;

    /**
     * Title (text)
     * Required: false
     * Id: f38fcf08-05b0-42fc-af1b-791103d5155c
     * Codename: title
     */
    title: Elements.TextElement;
}>;
