/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: 🧳JG Travel Group [POC]
 * Environment: Production
 * Project Id: 33fb2a06-4e47-0171-c093-534525a700c7
 */
export const assetFolders = {} as const;
