/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const assetFolders = {
    /**
     * JG Travel Group   Brand Assets
     */
    jGTravelGroupBrandAssets: {
        id: '492b3bd1-33ec-44b6-8dbd-a9dc75e347e1',
        name: 'JG Travel Group - Brand Assets',
        externalId: undefined,
        folders: {}
    },

    /**
     * Just Go   Brand Assets
     */
    justGoBrandAssets: {
        id: 'e3d29346-f4db-4bf6-9053-59f0cc8064e7',
        name: 'Just Go - Brand Assets',
        externalId: undefined,
        folders: {
            /**
             * Logo   Print
             */
            logoPrint: {
                id: '4164c111-1dff-474c-b3cf-d4b1af9f94e8',
                name: 'Logo - Print',
                externalId: undefined,
                folders: {}
            },

            /**
             * Logo Web Versions
             */
            logoWebVersions: {
                id: 'c67fb2ce-8601-44c6-b024-2d93d88ae5ae',
                name: 'Logo Web Versions',
                externalId: undefined,
                folders: {}
            }
        }
    },

    /**
     * London   Photographs
     */
    londonPhotographs: {
        id: 'a6102a17-aeb2-4391-b302-43896b86d7bf',
        name: 'London - Photographs',
        externalId: undefined,
        folders: {}
    },

    /**
     * National Holidays   Brand Assets
     */
    nationalHolidaysBrandAssets: {
        id: '4209e5cd-f344-4349-b5cb-1da6b6da0d8f',
        name: 'National Holidays - Brand Assets',
        externalId: undefined,
        folders: {}
    }
} as const;
