/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: 🧳JG Travel Group [POC]
 * Environment: Production
 * Project Id: 33fb2a06-4e47-0171-c093-534525a700c7
 */
export const contentTypes = {
  /**
   * Excursion
   */
  excursion: {
    codename: 'excursion',
    id: '6a06cc0f-48d1-4716-8692-2fd1fc2ed3ba',
    externalId: undefined,
    name: 'Excursion',
    elements: {
      /**
       * Description (text)
       */
      description: {
        codename: 'description',
        id: '3882418b-92e4-470e-b323-790dfee359a3',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Duration (multiple_choice)
       */
      duration: {
        codename: 'duration',
        id: '03f9f273-7574-4e8b-8c97-b3d6d71b982a',
        externalId: undefined,
        name: 'Duration',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Name (text)
       */
      name: {
        codename: 'name',
        id: '3c4d3a14-410f-46be-9d29-b264991951ea',
        externalId: undefined,
        name: 'Name',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Price in £ pp (number)
       */
      price_in_pound_pp: {
        codename: 'price_in_pound_pp',
        id: 'ff1b07fd-9774-4479-bcb1-c04d36c0c99a',
        externalId: undefined,
        name: 'Price in £ pp',
        required: false,
        type: 'number',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Export Module
   */
  export_module: {
    codename: 'export_module',
    id: 'e85cbb10-843e-46c2-baa0-c78ac6297a4f',
    externalId: undefined,
    name: 'Export Module',
    elements: {
      /**
       * Export to CSV (custom)
       */
      export_to_csv: {
        codename: 'export_to_csv',
        id: '5b238f1e-0a58-43ea-9476-735fa9d31955',
        externalId: undefined,
        name: 'Export to CSV',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },

      /**
       * Include hotel data (multiple_choice)
       */
      include_hotel_data: {
        codename: 'include_hotel_data',
        id: 'fc7eee04-fea6-47c1-8a42-7bdabba42288',
        externalId: undefined,
        name: 'Include hotel data',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Tours to be exported (modular_content)
       */
      tours_to_be_exported: {
        codename: 'tours_to_be_exported',
        id: '4b804b94-c83c-4417-b752-7dfdd93c9b5b',
        externalId: undefined,
        name: 'Tours to be exported',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Hotel
   */
  hotel: {
    codename: 'hotel',
    id: 'a2f6a55d-8b15-428a-a271-148e3969a815',
    externalId: undefined,
    name: 'Hotel',
    elements: {
      /**
       * Accessibility information (text)
       */
      hotel_accessibility_information: {
        codename: 'hotel_accessibility_information',
        id: '85125ac7-71f9-4989-ba64-4ace0c853284',
        externalId: undefined,
        name: 'Accessibility information',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       */
      description: {
        codename: 'description',
        id: '7ba164ee-5657-434c-8bcc-3dee525cedb0',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Name (text)
       */
      name: {
        codename: 'name',
        id: '115f7825-6bd0-4025-874f-d8baa347a793',
        externalId: undefined,
        name: 'Name',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Rating (text)
       */
      rating: {
        codename: 'rating',
        id: 'abcdcf7f-dd3f-4973-a891-e626cb3731c3',
        externalId: undefined,
        name: 'Rating',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Page
   */
  page: {
    codename: 'page',
    id: 'fb007b3d-6b80-447a-a9ab-84bfda7ee473',
    externalId: undefined,
    name: 'Page',
    elements: {
      /**
       * Content (modular_content)
       */
      content: {
        codename: 'content',
        id: 'b17ae350-66b6-4b4a-ab79-6078ccb09bcc',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Show in navigation (multiple_choice)
       */
      show_in_navigation: {
        codename: 'show_in_navigation',
        id: '2b252d37-f2ec-4c54-907f-5ebb811037a3',
        externalId: undefined,
        name: 'Show in navigation',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: 'dba63878-8e20-4268-91a0-850c91ac91b2',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'da9b82ab-01c4-40ba-a3be-9b836f723ce9',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * URL (url_slug)
       */
      url: {
        codename: 'url',
        id: '6c83acf0-2866-4e16-ada0-3ee63137ab13',
        externalId: undefined,
        name: 'URL',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Place
   */
  place: {
    codename: 'place',
    id: 'a645c9b3-bee7-4f38-96f2-717ad3513cf9',
    externalId: undefined,
    name: 'Place',
    elements: {
      /**
       * Name (text)
       */
      name: {
        codename: 'name',
        id: '9a808484-cb90-40b6-8f58-0acbf79b8404',
        externalId: undefined,
        name: 'Name',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Tour
   */
  tour: {
    codename: 'tour',
    id: '89fd6a96-af63-4835-876b-e02977c676ee',
    externalId: undefined,
    name: 'Tour',
    elements: {
      /**
       * Accomodation(s) (modular_content)
       */
      hotel: {
        codename: 'hotel',
        id: '62a21c58-78ae-452c-9fb3-f5435ae4f091',
        externalId: undefined,
        name: 'Accomodation(s)',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       */
      description: {
        codename: 'description',
        id: '15d4c1ef-6ed2-4644-898e-69bf85f4ccae',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Duration in days (number)
       */
      duration_in_days: {
        codename: 'duration_in_days',
        id: '23970e05-7716-4c48-b065-53f15013bbf2',
        externalId: undefined,
        name: 'Duration in days',
        required: false,
        type: 'number',
        snippetCodename: undefined,
      },

      /**
       * End date (date_time)
       */
      end_date: {
        codename: 'end_date',
        id: 'bf3f80a9-18f7-447f-bcb7-f279009ca869',
        externalId: undefined,
        name: 'End date',
        required: false,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Export tour (custom)
       */
      export_tour: {
        codename: 'export_tour',
        id: 'd8c8beac-d1cd-4c43-b930-b89c15122a56',
        externalId: undefined,
        name: 'Export tour',
        required: false,
        type: 'custom',
        snippetCodename: undefined,
      },

      /**
       * Image(s) (asset)
       */
      image: {
        codename: 'image',
        id: '9b61ee67-5434-4fa9-bea4-b5db5e4c4a9c',
        externalId: undefined,
        name: 'Image(s)',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Included Excursion(s) (modular_content)
       */
      included_excursions: {
        codename: 'included_excursions',
        id: 'cf7257f4-8925-4875-b33a-38278d02f2be',
        externalId: undefined,
        name: 'Included Excursion(s)',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Includes (text)
       */
      includes: {
        codename: 'includes',
        id: 'e3b4b357-a051-4ca3-a367-db69ea5b02ab',
        externalId: undefined,
        name: 'Includes',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Name (text)
       */
      name: {
        codename: 'name',
        id: 'fa26cd34-0f57-4756-bd02-9f5678ff41c0',
        externalId: undefined,
        name: 'Name',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Optional Excursion(s) (modular_content)
       */
      optional_excursions: {
        codename: 'optional_excursions',
        id: 'fe67d8ad-2b4b-4cc4-afbc-f7dadb4b170a',
        externalId: undefined,
        name: 'Optional Excursion(s)',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Price in £ (number)
       */
      price: {
        codename: 'price',
        id: 'ac00a781-c9a3-4fa5-a61d-3458134b2fe2',
        externalId: undefined,
        name: 'Price in £',
        required: false,
        type: 'number',
        snippetCodename: undefined,
      },

      /**
       * Start date (date_time)
       */
      start_date: {
        codename: 'start_date',
        id: 'a7d6fe72-8c0c-4c75-b8ae-5cbe91ee40e4',
        externalId: undefined,
        name: 'Start date',
        required: false,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Tour number (text)
       */
      tour_number: {
        codename: 'tour_number',
        id: '46a2112b-c00d-42a6-9ea3-c488051a84a1',
        externalId: undefined,
        name: 'Tour number',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Web spotlight root
   */
  web_spotlight_root: {
    codename: 'web_spotlight_root',
    id: '9cea5a27-7770-4c25-9503-d64b99320d96',
    externalId: undefined,
    name: 'Web spotlight root',
    elements: {
      /**
       * Content (modular_content)
       */
      content: {
        codename: 'content',
        id: '4e26fcf1-a2fa-4f20-8b1d-37aba61452b6',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: '84450bcf-f1e2-4e3c-b6ea-8f07046dca51',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'bcc9b2b7-ed2c-4a8f-b766-15beb95e9f09',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },
} as const;
