/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: 🧳JG Travel Group [POC]
 * Environment: Production
 * Project Id: 33fb2a06-4e47-0171-c093-534525a700c7
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Default project language',
  },
} as const;
